# --------------
# -- Settings --
# --------------

url: "https://ivanzheng.tech"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: ""

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       ""
  description: ""
  image:       ""

# Event information.
event:
  name:        ""
  description: ""
  date:        ""
  location:    ""

  hero:
    links:
      # - text: "Linkedin"
      #   href: "https://www.linkedin.com/ivan-zheng-"
      - text: "Login"
        href: "login"
      - text: "Create Account"
        href: "createaccount"
    links2:
      - text: "Michael"
        href: "michael"
      - text: "Amber"
        href: "amber"
      - text: "david"
        href: "david"
      # - text: "wip"
      #   href: "seatalert"
      

  about:
    description: >
      Description 

  # Info Sections
  info:
    sections:
      - image: "images/sad-cowboy.png"
        title: "Hi."
        description: >
          H1
      - image: "images/sad-cowboy.png"
        title: "HI."
        description: >
          H2
      - image: "images/sad-cowboy.png"
        title: "HELLO."
        description: >
          H3


  # This is the message you'll receive once you've registered.
  register:
    message: >
      Placeholder

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
