# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: ""

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://ivanzheng14.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       ""
  description: ""
  image:       ""

# Event information.
event:
  name:        ""
  description: ""
  date:        ""
  location:    ""

  hero:
    links:
      - text: "Linkedin"
        href: "https://www.linkedin.com/ivan-zheng-"
      - text: "GitHub"
        href: "https://www.github.com/ivanzheng14"
      - text: "Contact me"
        href: "mailto:ivanzheng14@hotmail.com"
      

  about:
    description: >
      Example Hacks is a hackathon hosted at The University of Example.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.


  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
