# --------------
# -- Settings --
# --------------

url: "httpS://ivanzheng.me"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: ""

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       ""
  description: ""
  image:       ""

# Event information.
event:
  name:        ""
  description: ""
  date:        ""
  location:    ""

  hero:
    links:
      - text: "Linkedin"
        href: "https://www.linkedin.com/ivan-zheng-"
      - text: "GitHub"
        href: "https://www.github.com/ivanzheng14"
      - text: "Contact me"
        href: "mailto:ivanzheng14@hotmail.com"
      

  about:
    description: >
      Description 

  # Info Sections
  info:
    sections:
      - image: "images/sad-cowboy.png"
        title: "Hi."
        description: >
          H1
      - image: "images/sad-cowboy.png"
        title: "HI."
        description: >
          H2
      - image: "images/sad-cowboy.png"
        title: "HELLO."
        description: >
          H3


  # This is the message you'll receive once you've registered.
  register:
    message: >
      Placeholder

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
